[project]
name = "ok-star-resonanse"
version = "0.1.0"
requires-python = ">=3.12"
dependencies = [
    "certifi==2025.8.3",
    "charset-normalizer==3.4.2",
    "coloredlogs==15.0.1",
    "comtypes==1.4.11",
    "darkdetect==0.8.0",
    "flatbuffers==25.9.23",
    "humanfriendly==10.0",
    "idna==3.10",
    "mahjong-utils==0.7.7",
    "mido==1.3.3",
    "mini-racer==0.14.1",
    "mouse==0.7.1",
    "mpmath==1.3.0",
    "numpy==2.2.6",
    "ok-script==1.0.99",
    "onnxocr-ppocrv5==0.0.14",
    "onnxruntime-directml==1.24.4",
    "opencv-python==4.12.0.88",
    "openvino==2025.2.0",
    "openvino-telemetry==2025.2.0",
    "packaging==25.0",
    "pillow==11.3.0",
    "polib>=1.2.0",
    "protobuf==6.33.0",
    "psutil==7.0.0",
    "pyappify==1.0.2",
    "pycaw==20240210",
    "pyclipper==1.3.0.post6",
    "pydantic==1.10.26",
    "pydirectinput==1.0.4",
    "pynput==1.8.1",
    "pypushdeer==0.0.3",
    "pyreadline3==3.5.4",
    "pyside6==6.9.1",
    "pyside6-addons==6.9.1",
    "pyside6-essentials==6.9.1",
    "pyside6-fluent-widgets==1.8.3",
    "pysidesix-frameless-window==0.7.3",
    "pywin32==311",
    "requests==2.32.4",
    "shapely==2.1.1",
    "shiboken6==6.9.1",
    "six==1.17.0",
    "stringcase==1.2.0",
    "sympy==1.14.0",
    "typing-extensions==4.14.1",
    "urllib3==2.5.0",
    "zstandard>=0.23.0",
]
