syntax = "proto3";

package zproto;

// Minimal protocol definition.
message Position {
  float x = 1 [json_name = "x"];
  float y = 2 [json_name = "y"];
  float z = 3 [json_name = "z"];
  float dir = 4 [json_name = "dir"];
}

message Vector2 {
  optional float x = 1 [json_name = "x"];
  optional float y = 2 [json_name = "y"];
}

message Vector3 {
  optional float x = 1 [json_name = "x"];
  optional float y = 2 [json_name = "y"];
  optional float z = 3 [json_name = "z"];
}

message UserControlInfo {
  optional bool isBegin = 1 [json_name = "isBegin"];
  optional int32 type = 2 [json_name = "type"];
  optional int32 secondaryType = 3 [json_name = "secondaryType"];
  optional float remainTime = 4 [json_name = "remainTime"];
  optional int32 step = 5 [json_name = "step"];
  optional float horVelocity = 6 [json_name = "horVelocity"];
  optional float verVelocity = 7 [json_name = "verVelocity"];
  optional float pitchAngle = 8 [json_name = "pitchAngle"];
  optional int64 timeStamp = 9 [json_name = "timeStamp"];
  optional Vector2 runDir = 10 [json_name = "runDir"];
  optional Vector3 normal = 11 [json_name = "normal"];
  optional Position curPos = 12 [json_name = "curPos"];
  optional Position destPos = 13 [json_name = "destPos"];
  optional int32 moveVersion = 14 [json_name = "moveVersion"];
}

message NewMove {
  optional UserControlInfo info = 1 [json_name = "info"];
}

message SceneData {
  uint32 mapId = 1 [json_name = "mapId"];
  uint32 channelId = 2 [json_name = "channelId"];
  Position pos = 3 [json_name = "pos"];
}

message CharSerialize {
  int64 charId = 1 [json_name = "charId"];
  SceneData sceneData = 3 [json_name = "sceneData"];
}

message Attr {
  optional int32 id = 1 [json_name = "id"];
  optional bytes rawData = 2 [json_name = "rawData"];
}

message AttrCollection {
  optional int64 uuid = 1 [json_name = "uuid"];
  repeated Attr attrs = 2 [json_name = "attrs"];
}

message TempAttr {
  optional int32 id = 1 [json_name = "id"];
  optional int32 value = 2 [json_name = "value"];
}

message TempAttrCollection {
  repeated TempAttr attrs = 1 [json_name = "attrs"];
}

message BuffInfo {
  optional int32 buffUuid = 1 [json_name = "buffUuid"];
  optional int32 baseId = 2 [json_name = "baseId"];
  optional int32 level = 3 [json_name = "level"];
  optional int64 hostUuid = 4 [json_name = "hostUuid"];
  optional int64 createTime = 6 [json_name = "createTime"];
  optional int64 fireUuid = 7 [json_name = "fireUuid"];
  optional int32 layer = 8 [json_name = "layer"];
  optional int32 count = 10 [json_name = "count"];
  optional int32 duration = 11 [json_name = "duration"];
}

message BuffInfoSync {
  optional int64 uuid = 1 [json_name = "uuid"];
  repeated BuffInfo buffInfos = 2 [json_name = "buffInfos"];
}

message BuffChange {
  optional int32 layer = 1 [json_name = "layer"];
  optional int32 duration = 2 [json_name = "duration"];
  optional int64 createTime = 3 [json_name = "createTime"];
}

message BuffEffectLogicInfo {
  optional int32 effectType = 1 [json_name = "effectType"];
  optional bytes rawData = 2 [json_name = "rawData"];
}

message BuffEffect {
  optional int32 type = 1 [json_name = "type"];
  optional int32 buffUuid = 2 [json_name = "buffUuid"];
  optional int64 hostUuid = 3 [json_name = "hostUuid"];
  repeated BuffEffectLogicInfo logicEffect = 5 [json_name = "logicEffect"];
}

message BuffEffectSync {
  optional int64 uuid = 1 [json_name = "uuid"];
  repeated BuffEffect buffEffects = 2 [json_name = "buffEffects"];
}

message SkillCd {
  optional int32 skillLevelId = 1 [json_name = "skillLevelId"];
  optional int64 beginTime = 2 [json_name = "beginTime"];
  optional int32 duration = 3 [json_name = "duration"];
  optional int32 skillCdType = 4 [json_name = "skillCdType"];
  optional int32 validCdTime = 5 [json_name = "validCdTime"];
}

message Entity {
  optional int64 uuid = 1 [json_name = "uuid"];
  optional int32 entType = 2 [json_name = "entType"];
  optional AttrCollection attrs = 3 [json_name = "attrs"];
  optional TempAttrCollection tempAttrs = 4 [json_name = "tempAttrs"];
  optional BuffInfoSync buffInfos = 7 [json_name = "buffInfos"];
  optional BuffEffectSync buffEffect = 8 [json_name = "buffEffect"];
}

enum EDisappearType {
  EDisappearNone = 0;
  EDisappearDead = 1;
  EDisappearDestroy = 2;
  EDisappearTransferLeave = 3;
  EDisappearTransferPassLineLeave = 4;
}

message DisappearEntity {
  optional int64 uuid = 1 [json_name = "uuid"];
  optional EDisappearType type = 2 [json_name = "type"];
}

message SyncNearEntities {
  repeated Entity appear = 1 [json_name = "appear"];
  repeated DisappearEntity disappear = 2 [json_name = "disappear"];
}

message EnterSceneInfo {
  optional AttrCollection sceneAttrs = 1 [json_name = "sceneAttrs"];
  optional Entity playerEnt = 2 [json_name = "playerEnt"];
  optional string sceneGuid = 3 [json_name = "sceneGuid"];
  optional string connectGuid = 4 [json_name = "connectGuid"];
  optional AttrCollection subsceneAttrs = 5 [json_name = "subsceneAttrs"];
}

message AoiSyncDelta {
  optional int64 uuid = 1 [json_name = "uuid"];
  optional AttrCollection attrs = 2 [json_name = "attrs"];
  optional TempAttrCollection tempAttrs = 3 [json_name = "tempAttrs"];
  optional bytes buffEffect = 10 [json_name = "buffEffect"];
}

message AoiSyncToMeDelta {
  optional AoiSyncDelta baseDelta = 1 [json_name = "baseDelta"];
  repeated int64 syncHateIds = 2 [json_name = "syncHateIds"];
  repeated SkillCd syncSkillCDs = 3 [json_name = "syncSkillCDs"];
  optional int64 uuid = 5 [json_name = "uuid"];
}

message WorldNtf {
  message EnterScene {
    optional EnterSceneInfo enterSceneInfo = 1 [json_name = "enterSceneInfo"];
  }

  message SyncContainerData {
    CharSerialize vData = 1 [json_name = "vData"];
  }

  message SyncNearDeltaInfo {
    repeated AoiSyncDelta deltaInfos = 1 [json_name = "deltaInfos"];
  }

  message SyncToMeDeltaInfo {
    AoiSyncToMeDelta deltaInfo = 1 [json_name = "deltaInfo"];
  }
}

message TeamBaseInfo {
  optional int64 teamId = 1 [json_name = "teamId"];
  optional int64 leaderId = 3 [json_name = "leaderId"];
}

message TeamMemData {
  optional int64 charId = 1 [json_name = "charId"];
}

message TeamMemberFastSyncData {
  optional int64 charId = 1 [json_name = "charId"];
}

message NoticeUpdateTeamInfoRequest {
  optional TeamBaseInfo baseInfo = 1 [json_name = "baseInfo"];
}

message NoticeUpdateTeamInfo {
  optional NoticeUpdateTeamInfoRequest vRequest = 1 [json_name = "vRequest"];
}

message NoticeUpdateTeamMemberInfoRequest {
  repeated TeamMemberFastSyncData teamMemberSyncDatas = 5 [json_name = "teamMemberSyncDatas"];
  repeated TeamMemData teamMemberSocialDatas = 6 [json_name = "teamMemberSocialDatas"];
}

message NoticeUpdateTeamMemberInfo {
  optional NoticeUpdateTeamMemberInfoRequest vRequest = 1 [json_name = "vRequest"];
}

message NotifyJoinTeamRequest {
  optional TeamBaseInfo baseInfo = 1 [json_name = "baseInfo"];
  repeated TeamMemData memberData = 2 [json_name = "memberData"];
  map<int64, TeamMemberFastSyncData> memberSyncDatas = 6 [json_name = "memberSyncDatas"];
}

message NotifyJoinTeam {
  optional NotifyJoinTeamRequest vRequest = 1 [json_name = "vRequest"];
}

message NotifyLeaveTeamRequest {
  optional int64 charId = 1 [json_name = "charId"];
}

message NotifyLeaveTeam {
  optional NotifyLeaveTeamRequest vRequest = 1 [json_name = "vRequest"];
}

message NoticeTeamDissolve {
}
